# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-bullet-openstlinux"
BBFILE_PATTERN_meta-bullet-openstlinux = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-bullet-openstlinux = "6"

LAYERDEPENDS_meta-bullet-openstlinux = "core"
LAYERSERIES_COMPAT_meta-bullet-openstlinux = "scarthgap"
