# Distribution Information.
DISTRO = "infotainment"
DISTRO_NAME = "ABOU-Infotainment"
DISTRO_VERSION = "1.0"
MAINTAINER = "abdelrahman0abdellatif@gmail.com"

# SDK Information.
SDK_VENDOR = "-bulletSDK"
SDK_VERSION = "${@d.getVar('DISTRO_VERSION').replace('snapshot-${METADATA_REVISION}', 'snapshot')}"
SDK_VERSION[vardepvalue] = "${SDK_VERSION}"
SDK_NAME = "${DISTRO}-${TCLIBC}-${SDKMACHINE}-${IMAGE_BASENAME}-${TUNE_PKGARCH}-${MACHINE}"

# Installation path --> can be changed to ${HOME}-${DISTRO}-${SDK_VERSION}
SDKPATHINSTALL = "/opt/${DISTRO}/${SDK_VERSION}"

# Distribution Features --> used to add customized packages conditionally.
# infotainment --> INFOTAINMENT
INFOTAINMENT_DEFAULT_DISTRO_FEATURES = "largefile opengl multiarch vulkan wayland bluez5 bluetooth wifi qt6 pam"
INFOTAINMENT_DEFAULT_EXTRA_RDEPENDS = "packagegroup-core-boot"
INFOTAINMENT_DEFAULT_EXTRA_RRECOMMENDS = "kernel-module-af-packet"

DISTRO_FEATURES ?= "${DISTRO_FEATURES_DEFAULT} ${INFOTAINMENT_DEFAULT_DISTRO_FEATURES}"

DISTRO_FEATURES:remove = "x11" 

# systemd as init manager
require conf/distro/include/systemd.inc


# Kernel version pin (STM32MP257F-DK uses linux-stm32mp, not linux-yocto)
PREFERRED_VERSION_linux-stm32mp ?= "6.6%"


# Build System configuration.
LOCALCONF_VERSION = "2"

# Poky sanity checks
INHERIT += "poky-sanity"