# meta-bootlinlabs/conf/machine/my-bootlin-board.conf

# Inherit ST's common machine definitions for MP2
require conf/machine/include/st-machine-common-stm32mp.inc
require conf/machine/include/st-machine-providers-stm32mp.inc

# Include Cortex-A35 CPU tuning (ARMv8-A 64-bit)
require conf/machine/include/arm/armv8a/tune-cortexa35.inc
DEFAULTTUNE = "cortexa35"

# Inherit overrides so recipes for stm32mp25 apply to the custom board
MACHINEOVERRIDES =. "stm32mp2common:stm32mp25common:stm32mp25-disco:"

# Include device tree for STM32MP25 Disco board
STM32MP_DT_FILES_SDCARD = "stm32mp257f-dk"

# Optional hardware features
#MACHINE_FEATURES += "m33copro"